### ISSUE TITLE
user-select: none at the top page

### ISSUE THREAD

**Issue by tuttieee** [bmcmahen/sancho-docs#1]
Hello, thank you for the great work.

When I try to use the sample code, I couldn't copy that and it was useless.
Then I found `user-select: none` was set to `body` element and it seems derived from https://github.com/bmcmahen/sancho-docs/blob/d87ed8b607847dd22fff4e39d90448f13591c014/src/components/Layout.tsx#L59
I think it's better to remove this.

Thanks!

**Comment by bmcmahen** [comment]
Ohh, not sure what I was thinking. Will change this when I get the chance.
